PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?c WHERE {
  ?c rdf:type skos:Concept .
  FILTER NOT EXISTS { ?c skos:prefLabel ?l }
}
ORDER BY ?c
